<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="Vigneshs-MacBook-Air-3.local" name="SeleniumInterviewQuestions.ReRunFailedTestCases" tests="12" failures="0" timestamp="2020-09-15T16:53:18 IST" time="0.057" errors="2">
  <testcase name="secondTestCase" time="0.003" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- secondTestCase -->
  <testcase name="fourthTestCase" time="0.002" classname="SeleniumInterviewQuestions.ReRunFailedTestCases"/>
  <testcase name="thirdTestCase" time="0.002" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="secondTestCase" time="0.004" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- secondTestCase -->
  <testcase name="secondTestCase" time="0.004" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- secondTestCase -->
  <testcase name="thirdTestCase" time="0.006" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="thirdTestCase" time="0.003" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <error type="javax.management.RuntimeErrorException">
      <![CDATA[javax.management.RuntimeErrorException
at SeleniumInterviewQuestions.ReRunFailedTestCases.thirdTestCase(ReRunFailedTestCases.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- thirdTestCase -->
  <testcase name="secondTestCase" time="0.002" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- secondTestCase -->
  <testcase name="thirdTestCase" time="0.010" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="thirdTestCase" time="0.005" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <skipped/>
  </testcase> <!-- thirdTestCase -->
  <testcase name="firstTestCase" time="0.014" classname="SeleniumInterviewQuestions.ReRunFailedTestCases"/>
  <testcase name="secondTestCase" time="0.002" classname="SeleniumInterviewQuestions.ReRunFailedTestCases">
    <error type="javax.management.RuntimeErrorException">
      <![CDATA[javax.management.RuntimeErrorException
at SeleniumInterviewQuestions.ReRunFailedTestCases.secondTestCase(ReRunFailedTestCases.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- secondTestCase -->
</testsuite> <!-- SeleniumInterviewQuestions.ReRunFailedTestCases -->
